### ISSUE TITLE
StructureMap issue with 'IAsyncRequestHandler<Request, Response>'

### ISSUE THREAD

**Issue by igoshevski** [bojanv91/VERT#2]
Since I am new to StructureMap, I wasn't able to get through this issue. The issue occurs when I try to access http://localhost:24016/Users.

In debug mode, I am able to step into the Index action of the Users controller. When in the BaseMvcController class the Mediator.SendAsync is executed, I receive the following exception:

No default Instance is registered and cannot be automatically determined for type 'IAsyncRequestHandler<Request, Response>'

No default instance is specified.  The current configuration for type IAsyncRequestHandler<Request, Response> is:
Nested Container: DEFAULT - Nested

Exception Details: StructureMap.StructureMapConfigurationException: No default Instance is registered and cannot be automatically determined for type 'IAsyncRequestHandler<Request, Response>'

**Comment by bojanv91** [comment]
Added ``AppServices`` assembly to the StructureMap scanner in ``MediatorPipelineRegistry``.
I told SM what types to scan, but did not tell in which assemblies to scan them during the latest assembly restructuring.

In StructureMap there are two very helpful diagnostic methods which are perfect for debugging:
string whatdidiscan = Container.WhatDidIScan();
string whatdoihave = Container.WhatDoIHave();

I put them in ``Bootstrapper.cs``, so you can check what does SM know under the hood about our registered types.
